version: '3.8'

services:
  backend:
    env_file: .env
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./project.db:/opt/app/project.db

  frontend:
    image: painassasin/node_cource_project
    ports:
      - "80:80"
